'use client'

import { useState } from 'react'
import { format } from 'date-fns'
import { fr } from 'date-fns/locale'

// ─── Types ────────────────────────────────────────────────────────────────────
type PubType = 'journal' | 'conference' | 'book_chapter' | 'preprint' | 'report'

interface Publication {
  id:         string
  type:       PubType
  title:      string
  authors:    string[]
  venue:      string
  year:       number
  doi:        string | undefined
  citations:  number
  hal:        string | undefined
  abstract:   string
}

// ─── Demo data ────────────────────────────────────────────────────────────────
const PUBLICATIONS: Publication[] = [
  {
    id: 'p1',
    type: 'journal',
    title: 'Federated Learning under Byzantine Failures: A Differential Privacy Approach',
    authors: ['A. Martin', 'E. Fontaine', 'L. Zhao'],
    venue: 'IEEE Transactions on Neural Networks and Learning Systems',
    year: 2025,
    doi: '10.1109/TNNLS.2025.00134',
    citations: 42,
    hal: 'hal-04521673',
    abstract: 'This paper proposes FedDP-Guard, a novel framework combining differential privacy with robust aggregation to defend against Byzantine clients in federated learning settings. We prove strong privacy guarantees and demonstrate empirical resilience on benchmark datasets.',
  },
  {
    id: 'p2',
    type: 'conference',
    title: 'Adaptive Clustering for High-Dimensional Data Streams in Edge Computing',
    authors: ['A. Martin', 'R. Dupont'],
    venue: 'NeurIPS 2024 — 38th Annual Conference on Neural Information Processing Systems',
    year: 2024,
    doi: '10.5555/3666327.3666398',
    citations: 27,
    hal: 'hal-04312845',
    abstract: 'We introduce StreamClust, an online clustering algorithm tailored for resource-constrained edge devices. StreamClust achieves sub-linear memory complexity while maintaining competitive clustering quality.',
  },
  {
    id: 'p3',
    type: 'journal',
    title: 'Security Analysis of REST APIs in Microservice Architectures: A Systematic Review',
    authors: ['A. Martin', 'S. Nakamura', 'P. Leroy'],
    venue: 'ACM Computing Surveys',
    year: 2024,
    doi: '10.1145/3614103',
    citations: 61,
    hal: 'hal-04198765',
    abstract: 'A comprehensive review of 147 papers on REST API security, covering authentication, authorization, and injection vulnerabilities in microservice architectures. We propose a taxonomy and identify open research challenges.',
  },
  {
    id: 'p4',
    type: 'conference',
    title: 'Graph Neural Networks for Network Intrusion Detection: Benchmark and Analysis',
    authors: ['A. Martin', 'H. Garnier', 'C. Petit'],
    venue: 'IEEE International Conference on Computer Communications (INFOCOM 2024)',
    year: 2024,
    doi: '10.1109/INFOCOM52122.2024.10621413',
    citations: 18,
    hal: 'hal-04287654',
    abstract: 'We benchmark six state-of-the-art GNN architectures for network intrusion detection on the CIC-IDS2018 dataset and introduce a novel heterogeneous graph formulation.',
  },
  {
    id: 'p5',
    type: 'book_chapter',
    title: 'Deep Learning for Cybersecurity: Foundations and Applications',
    authors: ['A. Martin'],
    venue: 'Handbook of Applied Machine Learning (Springer), Chapter 12',
    year: 2023,
    doi: '10.1007/978-3-031-12345-6_12',
    citations: 35,
    hal: undefined,
    abstract: 'A comprehensive survey of deep learning techniques applied to cybersecurity problems including malware detection, intrusion detection, and vulnerability analysis.',
  },
  {
    id: 'p6',
    type: 'preprint',
    title: 'LLM Code Generation Safety: Evaluating Vulnerability Propagation in Production Pipelines',
    authors: ['A. Martin', 'O. Khalil', 'F. Renaud'],
    venue: 'arXiv:2506.01234 [cs.CR]',
    year: 2026,
    doi: undefined,
    citations: 3,
    hal: 'hal-04612345',
    abstract: 'We systematically evaluate the security posture of code generated by large language models when integrated into CI/CD pipelines. Our analysis reveals that 34% of LLM-generated code contains at least one CWE-Top-25 vulnerability.',
  },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────
function pubTypeInfo(t: PubType): { label: string; cls: string } {
  const map: Record<PubType, { label: string; cls: string }> = {
    journal:      { label: 'Revue',          cls: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300' },
    conference:   { label: 'Conférence',     cls: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300' },
    book_chapter: { label: 'Chap. livre',    cls: 'bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300' },
    preprint:     { label: 'Preprint',       cls: 'bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300' },
    report:       { label: 'Rapport',        cls: 'bg-muted text-muted-foreground' },
  }
  return map[t]
}

// ─── Add Publication Modal ────────────────────────────────────────────────────
function AddPubModal({ onClose }: { onClose: () => void }) {
  const [form, setForm] = useState({
    type: 'journal' as PubType,
    title: '',
    authors: '',
    venue: '',
    year: String(new Date().getFullYear()),
    doi: '',
  })
  const [saved, setSaved] = useState(false)

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setSaved(true)
    setTimeout(onClose, 1500)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
      <div className="w-full max-w-lg rounded-2xl bg-card p-6 shadow-xl">
        <h3 className="font-semibold">Ajouter une publication</h3>

        {saved ? (
          <div className="mt-6 text-center">
            <p className="text-2xl">✅</p>
            <p className="mt-2 font-medium text-emerald-600">Publication ajoutée !</p>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="mt-4 space-y-3">
            <div>
              <label className="mb-1 block text-xs font-medium text-muted-foreground">Type</label>
              <select
                value={form.type}
                onChange={e => setForm(f => ({ ...f, type: e.target.value as PubType }))}
                className="w-full rounded-lg border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
              >
                <option value="journal">Article de revue</option>
                <option value="conference">Communication de conférence</option>
                <option value="book_chapter">Chapitre de livre</option>
                <option value="preprint">Preprint / arXiv</option>
                <option value="report">Rapport technique</option>
              </select>
            </div>
            <div>
              <label className="mb-1 block text-xs font-medium text-muted-foreground">Titre</label>
              <input
                type="text"
                required
                value={form.title}
                onChange={e => setForm(f => ({ ...f, title: e.target.value }))}
                placeholder="Titre complet de la publication"
                className="w-full rounded-lg border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
            </div>
            <div>
              <label className="mb-1 block text-xs font-medium text-muted-foreground">Auteurs (séparés par virgule)</label>
              <input
                type="text"
                required
                value={form.authors}
                onChange={e => setForm(f => ({ ...f, authors: e.target.value }))}
                placeholder="A. Martin, B. Dupont, …"
                className="w-full rounded-lg border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
            </div>
            <div>
              <label className="mb-1 block text-xs font-medium text-muted-foreground">Revue / Conférence / Éditeur</label>
              <input
                type="text"
                required
                value={form.venue}
                onChange={e => setForm(f => ({ ...f, venue: e.target.value }))}
                placeholder="ex. IEEE Transactions on …"
                className="w-full rounded-lg border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
            </div>
            <div className="grid gap-3 grid-cols-2">
              <div>
                <label className="mb-1 block text-xs font-medium text-muted-foreground">Année</label>
                <input
                  type="number"
                  min="1990"
                  max="2030"
                  required
                  value={form.year}
                  onChange={e => setForm(f => ({ ...f, year: e.target.value }))}
                  className="w-full rounded-lg border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
              </div>
              <div>
                <label className="mb-1 block text-xs font-medium text-muted-foreground">DOI (optionnel)</label>
                <input
                  type="text"
                  value={form.doi}
                  onChange={e => setForm(f => ({ ...f, doi: e.target.value }))}
                  placeholder="10.xxxx/…"
                  className="w-full rounded-lg border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
              </div>
            </div>
            <div className="flex gap-2 pt-1">
              <button
                type="button"
                onClick={onClose}
                className="flex-1 rounded-lg border px-3 py-2 text-sm hover:bg-muted"
              >
                Annuler
              </button>
              <button
                type="submit"
                className="flex-1 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-medium text-white hover:bg-indigo-700"
              >
                Ajouter
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  )
}

// ─── Publication Card ─────────────────────────────────────────────────────────
function PubCard({ pub }: { pub: Publication }) {
  const [expanded, setExpanded] = useState(false)
  const { label, cls } = pubTypeInfo(pub.type)

  return (
    <div className="rounded-xl border bg-card p-4 shadow-sm hover:shadow-md transition-shadow">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2 mb-1.5">
            <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${cls}`}>{label}</span>
            <span className="text-xs text-muted-foreground">{pub.year}</span>
            <span className="flex items-center gap-1 text-xs text-muted-foreground">
              <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
              </svg>
              {pub.citations} citation{pub.citations !== 1 ? 's' : ''}
            </span>
          </div>
          <p className="font-semibold leading-snug">{pub.title}</p>
          <p className="mt-0.5 text-sm text-muted-foreground">{pub.authors.join(', ')}</p>
          <p className="mt-0.5 text-xs text-muted-foreground italic">{pub.venue}</p>
        </div>
      </div>

      {expanded && (
        <p className="mt-3 rounded-lg bg-muted/50 p-3 text-sm text-muted-foreground">{pub.abstract}</p>
      )}

      <div className="mt-3 flex flex-wrap items-center gap-2">
        <button
          onClick={() => setExpanded(v => !v)}
          className="rounded border px-2.5 py-1 text-xs font-medium hover:bg-muted"
        >
          {expanded ? 'Masquer' : 'Résumé'}
        </button>
        {pub.doi && (
          <span className="rounded border px-2.5 py-1 text-xs font-mono text-muted-foreground">
            DOI: {pub.doi}
          </span>
        )}
        {pub.hal && (
          <span className="rounded border border-blue-200 bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700 dark:border-blue-800 dark:bg-blue-950/20 dark:text-blue-400">
            {pub.hal}
          </span>
        )}
      </div>
    </div>
  )
}

// ─── Main Component ───────────────────────────────────────────────────────────
export function TeacherPublications() {
  const [filterType, setFilterType] = useState<PubType | 'all'>('all')
  const [showAdd,    setShowAdd]    = useState(false)

  const filtered = filterType === 'all'
    ? PUBLICATIONS
    : PUBLICATIONS.filter(p => p.type === filterType)

  // Stats
  const totalCitations = PUBLICATIONS.reduce((sum, p) => sum + p.citations, 0)
  const hIndex = (() => {
    const sorted = [...PUBLICATIONS].sort((a, b) => b.citations - a.citations)
    let h = 0
    for (let i = 0; i < sorted.length; i++) {
      if ((sorted[i]?.citations ?? 0) >= i + 1) h = i + 1
      else break
    }
    return h
  })()

  const TYPE_FILTERS: Array<{ value: PubType | 'all'; label: string }> = [
    { value: 'all',         label: 'Toutes' },
    { value: 'journal',     label: 'Revues' },
    { value: 'conference',  label: 'Conférences' },
    { value: 'book_chapter',label: 'Chapitres' },
    { value: 'preprint',    label: 'Preprints' },
  ]

  return (
    <div className="space-y-6">

      {showAdd && <AddPubModal onClose={() => setShowAdd(false)} />}

      {/* Header */}
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">Mes publications</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Portail IRIS / HAL · {PUBLICATIONS.length} publications référencées
          </p>
        </div>
        <button
          onClick={() => setShowAdd(true)}
          className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700"
        >
          + Ajouter
        </button>
      </div>

      {/* Stats strip */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        {[
          { label: 'Publications',  value: PUBLICATIONS.length, color: 'text-indigo-600'  },
          { label: 'h-index',       value: hIndex,              color: 'text-violet-600'  },
          { label: 'Citations',     value: totalCitations,      color: 'text-blue-600'    },
          { label: 'Cette année',   value: PUBLICATIONS.filter(p => p.year >= 2026).length, color: 'text-emerald-600' },
        ].map(k => (
          <div key={k.label} className="rounded-xl border bg-card p-4 shadow-sm">
            <p className={`text-2xl font-bold ${k.color}`}>{k.value}</p>
            <p className="mt-0.5 text-xs text-muted-foreground">{k.label}</p>
          </div>
        ))}
      </div>

      {/* Filter tabs */}
      <div className="flex flex-wrap gap-1.5">
        {TYPE_FILTERS.map(f => (
          <button
            key={f.value}
            onClick={() => setFilterType(f.value)}
            className={`rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${
              filterType === f.value
                ? 'bg-indigo-600 text-white'
                : 'border hover:bg-muted text-muted-foreground'
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      {/* Publication list */}
      <div className="space-y-3">
        {filtered.map(pub => (
          <PubCard key={pub.id} pub={pub} />
        ))}
        {filtered.length === 0 && (
          <div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">
            Aucune publication dans cette catégorie.
          </div>
        )}
      </div>
    </div>
  )
}
